[phases.setup]
nixPkgs = ["php82", "nodejs_20", "php82Packages.composer"]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "cd backend && composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
  "cd backend && php artisan config:clear",
  "chmod -R 777 backend/storage",
  "chmod -R 777 backend/bootstrap/cache"
]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"
