[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
  "php artisan config:clear",
  "chmod -R 777 storage",
  "chmod -R 777 bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
